spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  profiles: dev

  jpa:
    hibernate:
      #当javabean的属性发生变化，自动更新数据库中的字段
      ddl-auto: update
    #将执行的sql语句显示到控制台
    show-sql: true

logging:
  #设置日志级别，项目根目录的级别为 info 我们自己的包下的日志级别为debug。指定日志存放的位置
  level:
    root: info
    com.maki: debug
  file:
    name: log/blog-dev.log

